---
  - name: RadFlow Setup Tool
    hosts: localhost
    connection: local
    vars:
        USER: "radflow"
        HOME_DIR: "/home/{{ USER }}"
        REPO_KEY_NAME: "id_rsa"
        GIT_REPO_DIR: "{{ HOME_DIR }}/radflow"
        GIT_REPO: "git@github.com:weklica/RT_Hermes.git"
        GIT_BRANCH: "develop"
        PYTHON_ENV_DIR: "{{ HOME_DIR }}/radflow-env"
        DB_NAME: "radflow"
        DB_USER: "radflow"
        DB_PASSWORD: "{{ lookup('password', 'db.pswd length=8') }}"
        DB_REDASH_USER: "redash"
        DB_REDASH_PASSWORD: "{{ lookup('password', 'db_redash.pswd length=8') }}"
        BOOKEEPER_CONF: "PORT=8080\nHOST=0.0.0.0\nDATABASE_URL=postgresql://{{ DB_USER }}:{{ DB_PASSWORD }}@localhost\n"
        WEBGUI_SECRET_KEY: "{{ lookup('password', 'webgui.secret length=15') }}"
        WEBGUI_CONF: "SECRET_KEY={{ WEBGUI_SECRET_KEY }}\nPORT=8000\nHOST=0.0.0.0\n"
    tasks:
      - name: Create user
        user:
          name: "{{ USER }}"
          shell: /bin/bash
          state: present
        tags:
          - "full-install"
      - name: Add github to known hosts
        lineinfile:
          dest: "{{ HOME_DIR }}/.ssh/known_hosts"
          create: yes
          state: present
          line: "{{ lookup('pipe', 'ssh-keyscan -t rsa github.com') }}"
          regexp: "^github\\.com"        
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Copy ssh key
        copy: 
          src: "{{ REPO_KEY_NAME }}"
          dest: "{{ HOME_DIR }}/.ssh/id_rsa"
          mode: 0600
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Cloning/Update the repo
        git:
          repo: "{{ GIT_REPO }}"
          dest: "{{ GIT_REPO_DIR }}"
          version: "{{ GIT_BRANCH }}"
          key_file: "{{ HOME_DIR }}/.ssh/id_rsa"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
          - "update"
          - "update-repo"
      - name: Install radflow
        shell: cd "{{ GIT_REPO_DIR }}/installation" && /bin/bash install.sh
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Install python packages
        pip:
          requirements: "{{ GIT_REPO_DIR }}/requirements.txt"
          executable: "{{ PYTHON_ENV_DIR }}/bin/pip"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
          - "update"
      - name: Copy service files
        copy: 
          src: "{{ GIT_REPO_DIR }}/installation/{{ item }}.service"
          dest: "/etc/systemd/system/{{ item }}.service"
        with_items:
          - "radflow_bookkeeper"
          - "radflow_cleaner"
          - "radflow_dispatcher"
          - "radflow_receiver"
          - "radflow_router"
          - "radflow_processor"
          - "radflow_ui"
        tags:
          - "full-install"
      - name: Enable services for radflow
        systemd:
          enabled: yes
          name: "{{ item }}.service"
        with_items:
          - "radflow_bookkeeper"
          - "radflow_cleaner"
          - "radflow_dispatcher"
          - "radflow_receiver"
          - "radflow_router"
          - "radflow_processor"
          - "radflow_ui"
        tags:
          - "full-install"
      - name: Make storage dirs
        file:
          path: "{{ HOME_DIR }}/{{ item }}"
          state: directory
          mode: "0755"
        with_items:
          - "radflow-data"
          - "radflow-data/incoming"
          - "radflow-data/outgoing"
          - "radflow-data/success"
          - "radflow-data/error"
          - "radflow-data/discard"
          - "radflow-data/processing"
          - "radflow-data/studies"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Create database
        postgresql_db:
          name: "{{ DB_NAME }}"
        become: yes
        become_user: postgres
        retries: 3
        delay: 5
        tags:
          - "full-install"
      - name: Create database user
        postgresql_user:
          db: "{{ DB_NAME }}"
          name: "{{ DB_USER }}"
          password: "{{ DB_PASSWORD }}"
          priv: "ALL"
        become: yes
        become_user: postgres
        tags:
          - "full-install"
      - name: Save db password
        copy:
          content: "{{ DB_PASSWORD }}"
          dest: "{{ HOME_DIR }}/db.pswd"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Create redash database user
        postgresql_user:
          name: "{{ DB_REDASH_USER }}"
          password: "{{ DB_REDASH_PASSWORD }}"
        become: yes
        become_user: postgres
        tags:
          - "full-install"
      - name: Save redash db password
        copy:
          content: "{{ DB_REDASH_PASSWORD }}"
          dest: "{{ HOME_DIR }}/db_redash.pswd"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Grant all priveleges to database for user radflow
        postgresql_privs:
          db: "{{ DB_NAME }}"
          privs: ALL
          type: database
          role: "{{ DB_USER }}"
        become: yes
        become_user: postgres
        tags:
          - "full-install"
      - name: Grant select priveleges to database for user redash
        postgresql_privs:
          db: "{{ DB_NAME }}"
          privs: "SELECT"
          type: table
          objs: ALL_IN_SCHEMA
          role: "{{ DB_REDASH_USER }}"
        become: yes
        become_user: postgres
        tags:
          - "full-install"
      - name: Configure bookkeeper
        copy: 
          content: "{{ BOOKEEPER_CONF }}"
          dest: "{{ GIT_REPO_DIR }}/configuration/bookkeeper.env"
        tags:
          - "full-install"
      - name: Configure webgui
        copy: 
          content: "{{ WEBGUI_CONF }}"
          dest: "{{ GIT_REPO_DIR }}/configuration/webgui.env"
        tags:
          - "full-install"
      - name: Starting a services
        systemd:
          name: "{{ item }}.service"
          state: started
        with_items:
          - "radflow_bookkeeper"
          - "radflow_ui"
          - "radflow_cleaner"
          - "radflow_dispatcher"
          - "radflow_receiver"
          - "radflow_router"          
          - "radflow_processor"
        tags:
          - "full-install"
      - name: Migration DB
        shell: 
          chdir: "{{ GIT_REPO_DIR }}"
          cmd: "{{ PYTHON_ENV_DIR }}/bin/alembic upgrade head"
          environment:
            PYTHONPATH: "{{ GIT_REPO_DIR }}"
          become: yes
          become_user: "{{ USER }}"
          tags:
            - "full-install"
            - "update"
            - "migrate"
      - include: "disposable_tasks.yaml"
      - name: Re-starting a services
        systemd:
          name: "{{ item }}.service"
          state: restarted
        with_items:
          - "radflow_bookkeeper"
          - "radflow_ui"
          - "radflow_cleaner"
          - "radflow_dispatcher"
          - "radflow_receiver"
          - "radflow_router"
          - "radflow_processor"
        tags:
          - "update"
          - "restart-radflow"
      - name: Download redash install script
        get_url:
          url: "https://raw.githubusercontent.com/getredash/setup/master/setup.sh"
          dest: "{{ HOME_DIR }}/setup.sh"
        become: yes
        become_user: "{{ USER }}"
        tags:
          - "full-install"
      - name: Install redash
        shell: cd "{{ HOME_DIR }}" && /bin/bash setup.sh
        tags:
          - "full-install"      
